feat: добавить сервис статистики
IvanPozhidaev/java-explore-with-me pull request #3
Opened 2023-08-03 12:30 UTC by IvanPozhidaev

2023-08-04 09:19 UTC, alexache requested changes

2023-08-04 09:19 UTC, alexache commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public ResponseEntity<Void> saveStats(String app, String uri, String ip, LocalDateTime dateTime) {
Для чего тут ResponseEntity?

2023-08-04 09:19 UTC, alexache commented on stats/server/src/main/java/ru/practicum/ewm/stats/model/HitModel.java
> +@Data
Нельзя использовать эту аннотацию на JPA модели, потому что оно включает в себя @EqualsAndHashcode

2023-08-04 09:19 UTC, alexache commented on stats/server/src/main/java/ru/practicum/ewm/stats/repository/StatsRepositoryJpa.java
> +    List<Object[]> findAll(LocalDateTime start, LocalDateTime end);
Как-то не очень красиво перекладывать в массив объектов, и для чего нативный запрос?

2023-08-05 02:23 UTC, IvanPozhidaev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public ResponseEntity<Void> saveStats(String app, String uri, String ip, LocalDateTime dateTime) {
Убрано.

2023-08-05 02:28 UTC, IvanPozhidaev commented on stats/server/src/main/java/ru/practicum/ewm/stats/model/HitModel.java
> +@Data
Переделано.

2023-08-05 02:41 UTC, IvanPozhidaev commented on stats/client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Сделано.

2023-08-05 02:52 UTC, IvanPozhidaev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +            Map<String, Object> parametersUris = Map.of("start", encodeDateTime(start), "end", encodeDateTime(end), "uris", uris, "unique", uniq);
Переделано

2023-08-05 02:52 UTC, IvanPozhidaev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public List<StatsDto> getStats(LocalDateTime start, LocalDateTime end, @Nullable String[] uris, @Nullable boolean uniq) {
Переделано.

2023-08-07 12:10 UTC, alexache approved these changes

2023-08-07 16:39 UTC, merged