Main svc
IvanPozhidaev/java-explore-with-me pull request #4
Opened 2023-08-14 14:23 UTC by IvanPozhidaev

2023-08-15 20:42 UTC, alexache requested changes

2023-08-15 20:42 UTC, alexache commented on main/pom.xml
> +            <version>${querydsl.version}</version>
Версии библиотек должны быть только в родительском модуле

2023-08-15 20:42 UTC, alexache commented on main/pom.xml
> +                <version>1.1.3</version>
Как и версии плагинов - в pluginManagement

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/controller/AdminEventController.java
> +        log.info("[GET /admin/events?users={users}&states={states}&categories={categories}&rangeStart={rangeStart}&rangeEnd={rangeEnd}&from={from}&size={size}] (Admin). " +
Однако, длинное лог сообщение

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/dto/CommentDto.java
> +public class CommentDto {
Это относится к следующему этапу? Лучше пока убрать

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/dto/CompilationDto.java
> +    private List<Event> events;
ДТО и Модели не должны смешиваться в одном классе. Значит здесь должны использоваться какие-то из ДТО событий

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/dto/CompilationUpdateDto.java
> +    private List<Event> events;
Такой же нюанс с моделями в ДТО

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/dto/EventDtoFull.java
> +public class EventDtoFull extends EventShortDto {
Название должно заканчиваться на Dto

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/entity/Event.java
> +    private Integer confirmedRequests;
Это не должно храниться в данной таблице - есть своя отдельная таблица с заявками

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/repository/CategoryRepository.java
> +@EnableJpaRepositories
А зачем эта конфигурационная аннотация на классах репозиториев?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/CompilationService.java
> +            if (pinned) {
Почему бы просто не передать pinned в метод репозитория? Зачем этот иф-елс?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/RequestService.java
> +            event.setConfirmedRequests(confirmed + 1);
Плохая и опасная арифметика, лучше полагаться на таблицу с заявками

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/RequestService.java
> +            return new ArrayList<>();
более подойдет тут Collections.emptyList() чтобы не плодить объекты

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/RequestService.java
> +        request.setStatus(RequestStatus.CANCELED);
СТоит ли проверять предыдущий статус заявки?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/UserService.java
> +            return result.size() == 0 ? List.of() : UserConverter.mapToDto(result);
выглядит как общая часть с тем, что после иф

2023-08-15 20:42 UTC, alexache commented on stats/client/pom.xml
> +                    <source>10</source>
интересный выбор версии

2023-08-15 20:42 UTC, alexache commented on stats/dto/pom.xml
> +        <version>2.7.5</version>
Не должно быть версий нигде, кроме родительского модуля

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +        if (duration.toSeconds() <= 7200) {
Почему именно секунды, не минуты, часы?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +        var allRequests = event.getAllRequests().stream()
Зачем брать все запросы, а не только те, которые нужны?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +                        var rSaved = requestRepository.save(r);
Лучше не вызывать сохранение в цикле, а вызвать saveAll после

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +        eventRepository.findAll(predicateAdmin).forEach(foundEventsAdmin::add);
почему не коллектором?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +        List<Event> pageList = foundEventsAdmin.stream()
Пагинация обычно для запросов к базе, а не к полученным в джаве данным

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +                        .sorted(Comparator.comparing(this::getViews).reversed())
Сортировка по количеству просмотров до того, как добавили информацию о количестве просмотров?

2023-08-15 20:42 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +    public EventDtoFull getEventByIdPublic(Long id, HttpServletRequest request) {
Лучше бы ip и uri передавать на вход метода вместо стороннего объекта

2023-08-17 08:33 UTC, IvanPozhidaev commented on main/src/main/java/ru/practicum/ewm/dto/CommentDto.java
> +public class CommentDto {
Да, сразу начал с заделом на следующий этап. Убрал всё связанное с комментами.

2023-08-17 08:45 UTC, IvanPozhidaev commented on main/src/main/java/ru/practicum/ewm/dto/EventDtoFull.java
> +public class EventDtoFull extends EventShortDto {
Переделано.

2023-08-17 08:57 UTC, IvanPozhidaev commented on main/src/main/java/ru/practicum/ewm/controller/AdminEventController.java
> +        log.info("[GET /admin/events?users={users}&states={states}&categories={categories}&rangeStart={rangeStart}&rangeEnd={rangeEnd}&from={from}&size={size}] (Admin). " +
Сократил.

2023-08-19 17:50 UTC, alexache approved these changes

2023-08-19 17:50 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/repository/CompilationRepository.java
> +    @Query("select c from Compilation as c where (:pinned is null or c.pinned = :pinned)")
(опционально) проверку на null или true тоже можно сделать через именование метода

2023-08-19 17:50 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +                ? requests.stream().filter(request -> request.getStatus().equals(RequestStatus.CONFIRMED) ||
В этом списке и так только confirmed и pending? Если нет модерации, то такие заявки можно сразу делать confirmed, тогда и этот метод будет лишним - всегда считать CONFIRMED

2023-08-19 17:50 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +        List<Request> requestCountDtos = requestRepository.findByEventIdIn(foundEventsAdmin.stream().map(Event::getId).collect(Collectors.toList()));
Навеерное только confirmed и нужны?

2023-08-19 17:50 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +                Long count = collect.get(eventFullDto.getId());
Учитывая конструкцию ниже будет проще сразу делать getOrElse()

2023-08-19 17:50 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/service/EventService.java
> +        eventRepository.save(event);
А у события что поменялось?

2023-08-20 13:11 UTC, merged